login:
    defaults: { _controller: \AppBundle\Controller\LoginController::execute }
    path: /
    methods: [GET]

google_login:
     path: /login/check-google
     defaults: { _controller: \AppBundle\Controller\LoginController::responseGoogle }

home:
    path: /home
    defaults: { _controller: \AppBundle\Controller\HomeController::execute }