login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix: /

app:
    resource: "@AppBundle/Resources/config/routing.yml"



#login:
#    defaults: { _controller: \AppBundle\Controller\LoginController::execute }
#    path: /
#    methods: [GET]
#
#google_login:
#     path: /login/check-google
#     defaults: { _controller: \AppBundle\Controller\LoginController::responseGoogle }
#


#
#logout:
#  path: /logout
#  defaults: { _controller: \AppBundle\Controller\LogoutController::execute }


profile:
  resource: "@ProfileBundle/Resources/config/routing.yml"

