# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
         ROLE_ADMIN:       ROLE_USER
         ROLE_SUPER_ADMIN: ROLE_USER

    providers:
         fos_user:
              id: fos_user.user_provider.username_email
         in_memory:
              memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        main:
            pattern: ^/
            logout: true
            anonymous:    true
            form_login:
                 provider:   fos_user
               #  csrf_provider: form.csrf_provider
                 login_path: /login
                 check_path: /login_check

            oauth:
                 resource_owners:
                     google: "/login/check-google"
                 login_path:      /login

                 failure_path:    /login
                 oauth_user_provider:
                     service: my_user_provider
        login:
            pattern:  ^/login$
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
