spotify-login:
  path: /api/spotify/check-spotify
  defaults: { _controller: \AppBundle\Controller\ApiMusicalController::responseAuthorize }

api-search:
  path: /api/spotify/search
  defaults: { _controller: \AppBundle\Controller\ApiMusicalController::search }
  methods: [POST]

api-show-more:
  path: /api/spotify/search-more
  defaults: { _controller: \AppBundle\Controller\ApiMusicalController::searchMore }
  methods: [GET]

api-add-response:
  path: /api/spotify/response
  defaults: { _controller: \AppBundle\Controller\ApiMusicalController::addResponse }
  methods: [POST]

home:
  defaults: { _controller: \AppBundle\Controller\HomeController::index }
  path: /home
  methods: [GET]

save-comment:
  defaults: { _controller: \AppBundle\Controller\CommentController::save }
  path: /save-comment
  methods: [POST]

get-comments:
  defaults: { _controller: \AppBundle\Controller\CommentController::index }
  path: /comments
  methods: [GET]